### ISSUE TITLE
Setting kernel_settings_reboot_ok to true never reboots the server

### ISSUE THREAD

**Issue by timgriffiths** [linux-system-roles/kernel_settings#90]
I believe there is a bug in here, 

https://github.com/linux-system-roles/kernel_settings/blob/master/tasks/main.yml#L115

This line I believe should not be in the when clause, 

`- not kernel_settings_reboot_ok | d(false)`

or should be 

`- kernel_settings_reboot_ok | d(false)`

otherwise, the handler will never fire

**Comment by richm** [comment]
Thanks - please try https://github.com/linux-system-roles/kernel_settings/pull/93
note that the role only sets reboot_required if setting bootloader settings which isn't really supported https://github.com/linux-system-roles/kernel_settings/blob/master/library/kernel_settings.py#L449
We are hoping to have an actual bootloader (grub, uefi, etc.) at some point in the future - https://github.com/linux-system-roles/bootloader

**Comment by richm** [comment]
Fixed by #93
