### ISSUE TITLE
lookup plugin: first_found not found when using ansible-core 2.12.2  

### ISSUE THREAD

**Issue by mto79** [linux-system-roles/kernel_settings#95]
```
TASK [fedora.linux_system_roles.kernel_settings : Set platform/version specific variables] ************************************************
fatal: [xxxxxxxx]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'first_found'. Error was a <class 'KeyError'>, original message: 'Requested entry (plugin_type: lookup plugin: first_found setting: files ) was not defined in configuration.'. 'Requested entry (plugin_type: lookup plugin: first_found setting: files ) was not defined in configuration.'"}
```

**Comment by richm** [comment]
> ```
> TASK [fedora.linux_system_roles.kernel_settings : Set platform/version specific variables] ************************************************
> fatal: [xxxxxxxx]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'first_found'. Error was a <class 'KeyError'>, original message: 'Requested entry (plugin_type: lookup plugin: first_found setting: files ) was not defined in configuration.'. 'Requested entry (plugin_type: lookup plugin: first_found setting: files ) was not defined in configuration.'"}
> ```

What platform is your control node (i.e. where you installed ansible)?  What platform is the managed node?  How did you install ansible-core?  pip?  rpm? deb?

**Comment by mto79** [comment]
Hi Richard,

The platform for the control node is: Red Hat Enterprise Linux release 8.6 (Ootpa)
The platform for the managed node is also: Red Hat Enterprise Linux release 8.6 (Ootpa)

Ansible-core is comming from the offical repo (so rpm based):

ansible-core-2.12.2-3.1.el8.x86_64 : SSH-based configuration management, deployment, and task execution system
Repo        : rhel-8-for-x86_64-appstream-rpms
Matched from:
Provide    : ansible-core = 2.12.2-3.1.el8

ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.11.3
  libyaml = True

**Comment by mto79** [comment]
Everthing fine after update and can't reproduce in test env either .. so all good.

**Comment by richm** [comment]
> Everthing fine after update and can't reproduce in test env either .. so all good.

Thank you for your investigation - good to know - it was a problem with `ansible-core-2.12.2-3.1.el8.x86_64`? and upgrading to a later version fixed the issue?
